### ISSUE TITLE
да.

### ISSUE THREAD

**Issue by RomashkaTea** [VokesTeam/VokesBrawl-v34#2]
1. перед релизом на гитхаб советую удалять папки __pycache__
2. Logic/Helpers/get/getName.py это конечно что-то.. убери try except, поставь if packetID in packets (проверку на наличие айди в словаре (dict))
3. Logic/Helpers/get/gerErrorContext.py, сделай один словарь (dict) с двумя языками, должно получиться что-то вроде 
![image](https://user-images.githubusercontent.com/80623570/185610089-ee779fd8-ef6f-4f2f-a3b0-e754103c19c4.png)
4. thread per connection это bad
5. NotificationFactory работает совсем не так, фабрика должна создавать объект BaseNotiifcation и возвращать его, а не енкодить их (почему они статичные?)
6. Logic/Initial/Player.py, класс называется Players, должен называться Player, также try except тоже кринж, никаких src/config.json не может быть, ты main.py (или Core.py в данном случае) запускаешь не с /src, а с src/, также можно просто поставить проверку на наличие файла, и если нету то создавать новый
7. ещё много что, лень дальше расписывать

**Comment by SavokBS** [comment]
спасибо за ваш отзыв. наша команда в будущем попытается исправиться и учесть все ваши замечания!
